server:
  port: ${PORT:8081}
spring:
  application:
    name: api-catalog
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
  data:
    mongodb:
      database: catalogdevmongo
      port: 27017
      host: localhost
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}
management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
info:
  app:
    name: api catalogo
    version: 1.0.0
    description: Catálogo de películas

resilience4j.circuitbreaker:
  instances:
    clientMovie:
      allowHealthIndicatorToFail: false
      registerHealthIndicator: true
      slidingWindowSize: 5
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
    clientSerie:
      allowHealthIndicatorToFail: false
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

resilience4j.retry:
  instances:
    clientMovie:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - java.net.ConnectException
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
    clientSerie:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - java.net.ConnectException
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException